### ISSUE TITLE
print simulation progress for all strategies in multipleRuns

### ISSUE THREAD

**Issue by agojunior** [TerraME/calibration#128]
implement a way to multiple runs print a progress message according to the models execution:
"3/10 models executed."

**Comment by pedro-andrade-inpe** [comment]
Add a new parameter verbose = false (default). When true, it should print messages as above. To test that, use something like:

```
str = ""
oldprint = print
print = function(x) str = str..x end

-- do the test

unitTest:assertEquals(result, str)

print = oldprint
```

**Comment by agojunior** [comment]
This was already implemented for repeated a long time ago, I'm changing the name of this issue to represent what still has to be implemente (for the other strategies)

**Comment by pedro-andrade-inpe** [comment]
This issue was already solved by other issues.
